# https://buildbot.libretro.com/nightly/emscripten/RetroArch.7z

name: Flat

on:
  push:
    paths:
      - .github/workflows/flat.yml
  workflow_dispatch:
  schedule:
    - cron: "0 0 0 * *"

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      # This step installs Deno, which is a new Javascript runtime that improves on Node. We'll use it for postprocessing later
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
      # The third step is a Flat Action step. We fetch the data in the http_url and save it as downloaded_filename
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://buildbot.libretro.com/nightly/emscripten/RetroArch.7z # The data to fetch every 5 minutes
          downloaded_filename: retroarch.7z 
          postprocess: process.sh
          # mask: true # optional param to mask the source http_url from the commit. Look at README for more options
